// Even Fibonacci numbers
// Problem 2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

(function iife() {

  console.log('Problem 2')

  function evenFibNums() {
    const evenNums = [],
          max = 4000000;
    let a = 1,
        b = 0,
        temp;

    while (b <= max) {
      temp = a;
      a = a + b;
      b = temp;
      if (b % 2 === 0) evenNums.push(b);
    }

    return evenNums.reduce((a, b) => a + b);
  }

  console.log('Even Fibonacci numbers:', evenFibNums())

})()

// Answer: 4613732